# Generated by Django 4.2.7 on 2024-01-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ms18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORD_EMPLOYEE', models.CharField(max_length=100)),
                ('ORD_DATE_POSTED', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORD_NAME', models.CharField(max_length=200)),
                ('ORD_QUANTITY', models.IntegerField(default=0)),
                ('ORD_PRICE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ORD_DESCRIPTION', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_posted',
            new_name='PROD_DATE_POSTED',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='PROD_DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='PROD_NAME',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='PROD_IMAGE',
            field=models.ImageField(default='default.png', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='PROD_PRICE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='PROD_QUANTITY',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CART_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CART_QUANTITY', models.IntegerField(default=0)),
                ('CART_DATE_ADDED', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms18.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
